### ISSUE TITLE
Would you also share the fine-tuned ckpts?

### ISSUE THREAD

**Issue by HyeonHo99** [jjihwan/SV3D-fine-tune#1]
Great project!

Are you planning to also share the fine-tuned ckpts?

**Comment by jjihwan** [comment]
Thanks!

Actually, no.
This repository aims to reproduce the training code for SV3D, which has not been officially released.
I fine-tuned the model on fewer than 100 data points (that SV3D is already trained on) to check whether the code works well, so the fine-tuned checkpoints might be useless 😅
