### ISSUE TITLE
train shape x: torch.float32 torch.Size([1, 8, 72, 72]) y: torch.float32 torch.Size([21, 1280]) 

### ISSUE THREAD

**Issue by zhongjianlittlejiang** [jjihwan/SV3D-fine-tune#10]
sh scripts/sv3d_finetune.sh 
[rank0]:   File "/root/autodl-tmp/yankl/SV3D-fine-tune-main/sgm/modules/diffusionmodules/video_model.py", line 472, in forward
[rank0]:     assert y.shape[0] == x.shape[0]
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: AssertionError

[VideoUNet forward]
x: torch.float32 torch.Size([1, 8, 72, 72])
y: torch.float32 torch.Size([21, 1280])
How to ensure consistent input and output shapes？

**Comment by zhongjianlittlejiang** [comment]
sample pt file  x shape is [1,8,72,72], output y shape is [21,1280], to ensure consistency in shape，can you give some information?

**Comment by jjihwan** [comment]
The pt file should be encoded video, not an input frame.
x's shape would be [21, 8, 72, 72].
