### ISSUE TITLE
train model file  .ckpt  but inference  model file is .safetensors, inference need to change *.ckpt to *.safetensors?

### ISSUE THREAD

**Issue by zhongjianlittlejiang** [jjihwan/SV3D-fine-tune#11]
hello!we need to inference. but the  train model file is *.ckpt .   the inference model file is *.safetensors.  Do we need to use CKPT directly or convert CKPT to safetensors during the inference process?  the train model file name is last.ckpt. the inference model file name(ckpt path) is sv3d_p.safetensors.  
when we use
sh scripts/inference.sh
ckpt_path: checkpoints/sv3d_p.safetensors
inference.sh :
python3 scripts/sampling/simple_video_sample.py \
                            --version sv3d_p \
                            --input_path assets/fanta.png \
                            --verbose True
![simple_video_sample](https://github.com/user-attachments/assets/37740df1-89e4-4fe7-84d5-9ce29fbc6caa)
![sv3d_p](https://github.com/user-attachments/assets/882792b3-999c-47b5-80d8-acb4bf630bc7)

OR 
During the model training process, directly save the model as safetensors

last.ckpt     to         sv3d_p.safetensors

the training process:
model.save('*.safetensors')

**Comment by jjihwan** [comment]
Sorry for the late. Did you solve the problem? or need help?
