### ISSUE TITLE
What is the meaning of cond_aug

### ISSUE THREAD

**Issue by 2hiTee** [jjihwan/SV3D-fine-tune#12]
Hi, thanks for your work! I have a question, why need to add noise to the first frame condition? As shown in the sv3d pipeline, it did not show that any noise should be added to the first frame condition. Below is the code.
`cond_sigmas = torch.Tensor([1e-5]) ## ToDo`
`cond_frames = torch.rand_like(cond_frames_without_noise) * cond_sigmas + cond_frames_without_noise`

**Comment by jjihwan** [comment]
It is typical noise augmentation method proposed in [Cascaded Diffusion Models for High Fidelity Image Generation](https://arxiv.org/abs/2106.15282).
You can find the details in section 4.3 of SVD paper, since SV3D directly utilize SVD.

**Comment by 2hiTee** [comment]
> It is typical noise augmentation method proposed in [Cascaded Diffusion Models for High Fidelity Image Generation](https://arxiv.org/abs/2106.15282). You can find the details in section 4.3 of SVD paper, since SV3D directly utilize SVD.

Thanks for your reply! Thank you!
