### ISSUE TITLE
About the 3D reconstruction part of SV3D?

### ISSUE THREAD

**Issue by fengq1a0** [jjihwan/SV3D-fine-tune#4]
Thank you for this great project!

Do you know how to get the 3D reconstruction code of SV3D?
The first step: performing reconstruction from the generated images is easy.
However, the second step: Using Masked SDS Loss with SV3D seems not straightforward.

I may not have implemented the second step right. Would you happen to know any resources about this part?

**Comment by jjihwan** [comment]
Thank you for your interest and question.
In this project, we only consider the first stage of SV3D, which generates 21 orbit frames from a single input image.
Therefore, I currently have no information about the second step involving Masked SDS Loss with SV3D.

If you find the answer, please let me know.
