### ISSUE TITLE
About finetuning time cost.

### ISSUE THREAD

**Issue by Colezwhy** [jjihwan/SV3D-fine-tune#5]
Thank you for your great job! 
But would you please have a rough calculation of how much time it will cost to finetune a SV3D model with A6000 GPU?
Also, I wonder if it is possible to perform finetune on RTX3090 GPUs?
Much thanks again! That will be helpful!

**Comment by jjihwan** [comment]
Thank you for your kind words.

In our case, the training required 97% of the 48GB VRAM on an A6000 GPU and took roughly 10 hours to process 5 data points. I cannot confirm if it is possible with an RTX 3090, as I don't have access to one. If it does not work, you might try other memory-aware strategies.

**Comment by Colezwhy** [comment]
> Thank you for your kind words.
> 
> In our case, the training required 97% of the 48GB VRAM on an A6000 GPU and took roughly 10 hours to process 5 data points. I cannot confirm if it is possible with an RTX 3090, as I don't have access to one. If it does not work, you might try other memory-aware strategies.

Thank you very much for that. 
BTW, do you think that it is possible to accelerate SV3D with DDIM? 
Since the generation time is rather long for SV3D to get a 21 frame video and I am wondering how to accelerate that for more practical use.

**Comment by jjihwan** [comment]
I have no idea how to accelerate the inference without training. but you can try lower timesteps modifying the argument of the inference file.
If you can train the model, you might consider distillation or rectified flow.

**Comment by Colezwhy** [comment]
> I have no idea how to accelerate the inference without training. but you can try lower timesteps modifying the argument of the inference file. If you can train the model, you might consider distillation or rectified flow.

Thank you for that. Closing it now.
