### ISSUE TITLE
what's the data volume used in finetune?

### ISSUE THREAD

**Issue by KyrieYan1996** [jjihwan/SV3D-fine-tune#9]
Thanks for your amazing work.
1. I'm really wondering that how much data from objaverse-1.0 dataset is used in finetuning?
2. Should I use some specific folders like 000-000, 000-001(if so, pls advise me) or sample files from all folders?
Looking forward to your response. Thanks in advance

**Comment by jjihwan** [comment]
1. I just used a small subset of the Objaverse dataset to verify if the code work well.
2. You don't have to use that specific folder names; any names will work. However, you should use `orbit_frame_0020.png` and `orbit_frame.pt` for the files, which you can easily adjust in [here](https://github.com/jjihwan/SV3D-fine-tune/blob/b8f7b12fa40f79aa9be33d8a26312d4e6f36e913/sgm/data/dataset.py#L159).

**Comment by KyrieYan1996** [comment]
I really appreciate your reply as above. 
And I still have a minor query, do you perform any operations after retrieving the output(https://github.com/huggingface/diffusers/blob/8cdcdd9e32925200ce5e1cf410fe14a774f3c3a6/src/diffusers/models/autoencoders/autoencoder_kl_temporal_decoder.py#L335)? for example, times a coefficient(0.18215) like **0.18215 * moments**?
Many thanks

**Comment by jjihwan** [comment]
As I recall, I saved the results directly from the function. However, I'm not entirely sure, as I completed this project about five months ago. Please let me know whether the code works as expected or not
